export const mockClientes = [
  { nome: 'ROSA MARIA SOARES DE MORAIS' },
  { nome: 'RAFAEL DA ROCHA SANTOS' },
  { nome: 'T2 ASSESSORIA E CONSULTORIA CONTABIL E EMPRESARIAL LTDA' },
  { nome: 'TEVERE SOLUCOES CONTABEIS LTDA' },
  { nome: 'CONTABILIDADE DE EMPRESAS MINAS GERAIS LTDA' },
];
